apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-cricket-score-deployment
  labels:
    app: live-cricket-score
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-cricket-score
  template:
    metadata:
      labels:
        app: live-cricket-score
    spec:
      containers:
        - name: live-cricket-score-app
          image: gcr.io/basic-cabinet-466904-a5/live-cricket-score-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
              ephemeral-storage: 1Gi
            requests:
              cpu: 500m
              memory: 2Gi
              ephemeral-storage: 1Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - key: kubernetes.io/arch
          operator: Equal
          value: amd64
          effect: NoSchedule

---

apiVersion: v1
kind: Service
metadata:
  name: live-cricket-score-service
spec:
  selector:
    app: live-cricket-score
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
