apiVersion: apps/v1
kind: Deployment
metadata:
  name: cricket-score-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cricket-score-app
  template:
    metadata:
      labels:
        app: cricket-score-app
    spec:
      containers:
      - name: cricket-score-app
        image: gcr.io/basic-cabinet-466904/live-cricket-score-app:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cricket-score-service
spec:
  type: LoadBalancer
  selector:
    app: cricket-score-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
